### ISSUE TITLE
Incompatibility with ServerCore

### ISSUE THREAD

**Issue by ioanvl** [YUNG-GANG/YUNGs-API#29] opened 2022-04-07 21:24 UTC
HI, 

There is an incompatibility with [Servercore](https://modrinth.com/mod/servercore)

The game crashes with the minimum mods installed (fabric_api + cloth + yungs_api + servercore) with error:
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-api-lookup-api-v1'!
Exit Code: -1`

YUNG's API 2.0.7 - ServerCore 1.2.8 - Fabric Loader0.13.3/1.18.2

Both seem to try and modify similar paths
[latest.log](https://github.com/yungnickyoung/YUNGs-API/files/8446588/latest.log)

I've created a [mirror issue](https://github.com/Wesley1808/ServerCore/issues/24) on their git.

**Comment by yungnickyoung** [comment] 2022-05-16 18:13
Duplicate of #26 . Should be fixed in v2.0.8. Please open another issue if the problem persists

**Closed as completed by yungnickyoung** 2022-05-16 18:13 UTC
